

export const data = {
    barbers: [
      {
        id: 1,
        name: "Le Barbier Français",
        address: "123 Rue de la Paix, Paris, France",
        phone: "+33 1 23 45 67 89",
        rating: 4.8,
      },
      {
        id: 2,
        name: "Barber Shop Luxe",
        address: "456 Avenue des Champs-Élysées, Paris, France",
        phone: "+33 1 98 76 54 32",
        rating: 4.7,
      },
      {
        id: 3,
        name: "Gentleman's Barber",
        address: "789 Boulevard Saint-Germain, Paris, France",
        phone: "+33 1 55 66 77 88",
        rating: 4.9,
      },
      {
        id: 4,
        name: "Le Petit Barbier",
        address: "101 Rue Oberkampf, Paris, France",
        phone: "+33 1 22 33 44 55",
        rating: 4.6,
      },
      {
        id: 5,
        name: "Old School Barber",
        address: "202 Rue de Rivoli, Paris, France",
        phone: "+33 1 44 55 66 77",
        rating: 4.5,
      },
    ],
    hairdressers: [
      {
        id: 1,
        name: "Chic & Style",
        address: "123 Rue de la Mode, Lyon, France",
        phone: "+33 4 78 89 90 00",
        rating: 4.8,
      },
      {
        id: 2,
        name: "Salon Élégance",
        address: "456 Place Bellecour, Lyon, France",
        phone: "+33 4 72 34 56 78",
        rating: 4.7,
      },
      {
        id: 3,
        name: "Coupe Parfaite",
        address: "789 Rue de la Liberté, Lyon, France",
        phone: "+33 4 11 22 33 44",
        rating: 4.9,
      },
      {
        id: 4,
        name: "Coiffure Moderne",
        address: "101 Rue Victor Hugo, Lyon, France",
        phone: "+33 4 55 66 77 88",
        rating: 4.6,
      },
      {
        id: 5,
        name: "Hair Studio",
        address: "202 Quai de la Pêcherie, Lyon, France",
        phone: "+33 4 33 44 55 66",
        rating: 4.5,
      },
    ],
    manicures: [
      {
        id: 1,
        name: "Nail Artiste",
        address: "123 Rue du Vernissage, Marseille, France",
        phone: "+33 4 91 23 45 67",
        rating: 4.8,
      },
      {
        id: 2,
        name: "Beauté des Ongles",
        address: "456 Avenue de la Canebière, Marseille, France",
        phone: "+33 4 91 78 90 12",
        rating: 4.7,
      },
      {
        id: 3,
        name: "Manucure Chic",
        address: "789 Rue Paradis, Marseille, France",
        phone: "+33 4 91 55 66 77",
        rating: 4.9,
      },
      {
        id: 4,
        name: "Ongles et Beauté",
        address: "101 Rue de Rome, Marseille, France",
        phone: "+33 4 91 22 33 44",
        rating: 4.6,
      },
      {
        id: 5,
        name: "Institut des Ongles",
        address: "202 Rue de la République, Marseille, France",
        phone: "+33 4 91 33 44 55",
        rating: 4.5,
      },
    ],
    beautyInstitutes: [
      {
        id: 1,
        name: "Institut de Beauté Parisien",
        address: "123 Rue Montmartre, Paris, France",
        phone: "+33 1 40 20 30 40",
        rating: 4.8,
      },
      {
        id: 2,
        name: "Centre de Beauté Étoile",
        address: "456 Rue de la Fayette, Paris, France",
        phone: "+33 1 80 90 60 50",
        rating: 4.7,
      },
      {
        id: 3,
        name: "Spa & Beauté Paris",
        address: "789 Rue du Faubourg Saint-Honoré, Paris, France",
        phone: "+33 1 45 67 89 01",
        rating: 4.9,
      },
      {
        id: 4,
        name: "Institut Élégance",
        address: "101 Rue du Louvre, Paris, France",
        phone: "+33 1 30 40 50 60",
        rating: 4.6,
      },
      {
        id: 5,
        name: "Beauty Studio Paris",
        address: "202 Rue de la Paix, Paris, France",
        phone: "+33 1 20 30 40 50",
        rating: 4.5,
      },
    ],
  };
  